name: Deploy Grow Flow

on:
  push:
    branches: [ main ]

jobs:
  build-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install Pygbag
        run: |
          python -m pip install pygbag

      - name: Build Web Version
        run: |
          # On utilise --build pour générer les fichiers statiques
          # On retire --no_terminal qui cause l'erreur
          python -m pygbag --build .

      - name: Deploy Grow Flow to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: build/web
          branch: gh-pages
          clean: true
